name: grafana
services:
  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    user: "472:472"
    mem_limit: 128m
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.radinlab.com.br
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Authentik
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana-0edf664f8ab80b2d
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GRAFANA_OIDC_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid email profile
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.radinlab.com.br/application/o/authorize/
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=http://authentik-server:9000/application/o/token/
      - GF_AUTH_GENERIC_OAUTH_API_URL=http://authentik-server:9000/application/o/userinfo/
      - GF_AUTH_SIGNOUT_REDIRECT_URL=https://auth.radinlab.com.br/application/o/grafana/end-session/
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(groups[*], 'admin') && 'Admin' || 'Viewer'
    ports:
      - "3000:3000"
    volumes:
      - /DATA/storage1/grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      - radinlab
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/grafana.png
    x-casaos:
      ports:
        - container: "3000"
          description:
            en_us: "Grafana Web UI"
      volumes:
        - container: /var/lib/grafana
          description:
            en_us: "Grafana data"

networks:
  radinlab:
    external: true

x-casaos:
  architectures:
    - amd64
  main: grafana
  author: RadinLab
  category: Monitoring
  description:
    en_us: Observability dashboards for infrastructure monitoring.
  developer: Grafana Labs
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/grafana.png
  tagline:
    en_us: Dashboards and monitoring
  title:
    en_us: Grafana
  port_map: "3000"
  index: /
  scheme: http
