name: Proxmox Post-Install
on:
  workflow_dispatch:
  push:
    branches:
      - prod
      - dev
jobs:
  configure:
    runs-on: [self-hosted, "${{ github.ref_name }}"]
    if: github.ref_name == 'prod' || github.ref_name == 'dev'
    environment: ${{ github.ref_name }}
    env:
      ANSIBLE_HOST_KEY_CHECKING: "false"
    steps:
      - uses: actions/checkout@v4

      - name: Post-install Proxmox
        run: ansible-playbook -i "${{ vars.PROXMOX_HOST }}," -u root ansible/playbooks/proxmox-postinstall.yml

      - name: Configurar ACME + HTTPS 443
        env:
          ACME_EMAIL: ${{ vars.ACME_EMAIL }}
          PROXMOX_HOST: ${{ vars.PROXMOX_HOST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: ansible-playbook -i "${{ vars.PROXMOX_HOST }}," -u root ansible/playbooks/proxmox-acme.yml
