name: Proxmox Post-Install
on:
  workflow_dispatch:
  push:
    branches:
      - prod
      - dev
jobs:
  configure:
    runs-on: [self-hosted, "${{ github.ref_name }}"]
    if: github.ref_name == 'prod' || github.ref_name == 'dev'
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello World"
      - run: ansible-playbook -i "${{ vars.PROXMOX_HOST }}," -u root ansible/playbooks/proxmox-postinstall.yml
